"""add applications layer

Revision ID: 06be3ff03fba
Revises: ce5ae166ecb5
Create Date: 2026-06-01 09:00:41.481447
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '06be3ff03fba'
down_revision: str | None = 'ce5ae166ecb5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_name'), 'applications', ['name'], unique=False)
    op.create_index(op.f('ix_applications_slug'), 'applications', ['slug'], unique=True)
    op.add_column('projects', sa.Column('application_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_application_id'), 'projects', ['application_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_application_id'), table_name='projects')
    op.drop_column('projects', 'application_id')
    op.drop_index(op.f('ix_applications_slug'), table_name='applications')
    op.drop_index(op.f('ix_applications_name'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
