"""add iast sessions

Revision ID: ce5ae166ecb5
Revises: 90133a1238fb
Create Date: 2026-05-31 23:12:03.082325
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ce5ae166ecb5'
down_revision: str | None = '90133a1238fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iast_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('runtime', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('collector_token_ref', sa.String(), nullable=False),
    sa.Column('collector_token_hash', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iast_sessions_project_id'), 'iast_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_iast_sessions_scan_id'), 'iast_sessions', ['scan_id'], unique=False)
    op.create_index(op.f('ix_iast_sessions_status'), 'iast_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iast_sessions_status'), table_name='iast_sessions')
    op.drop_index(op.f('ix_iast_sessions_scan_id'), table_name='iast_sessions')
    op.drop_index(op.f('ix_iast_sessions_project_id'), table_name='iast_sessions')
    op.drop_table('iast_sessions')
    # ### end Alembic commands ###
